name: Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
env:
  MONGO_URI: ${{ vars.MONGO_URI }}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4
      - name: check files
        run: ls

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: installing
        run: npm install

      - name: unit testing
        run: npm test

      - name: Archive Test Result
        uses: actions/upload-artifact@v4
        with:
          name: mocha-test-results
          path: test-results.xml

      - name: status
        run: echo "success"
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup node js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install
        run: npm install
      - name: check code coverage
        run: npm run coverage

      - name: Archive Coverage Reports
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage
          retention-days: 5
