name: Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
jobs:
  build_test:
    env:
      MONGO_URI: ${{ vars.MONGO_URI }}
      MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: check files
        run: ls

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install
        run: npm install

      - name: debug
        run: echo "Connecting to $MONGO_URI as $MONGO_USERNAME"

      - name: run test
        run: npm test

      - name: status
        run: echo "success"
