name: Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
env:
  MONGO_URI: ${{ vars.MONGO_URI }}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
  build_test:
#    strategy:
#      matrix:
#        versions: [18,20]
#        os: [ubuntu-latest,windows-latest]
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4
      - name: check files
        run: ls

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install
        run: npm install

      - name: debug
        run: echo "Connecting to $MONGO_URI as $MONGO_USERNAME"

      - name: unit testing
        run: npm test

      - name: Archive Test Result
        uses: actions/upload-artifact@v4
        with:
          name: mocha-test-results
          path: test-results.xml

      - name: status
        run: echo "success"
