name: Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
env:
  MONGO_URI: ${{ vars.MONGO_URI }}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:

  build_test:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4
      - name: check files
        run: ls

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path:  node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: installing
        run: npm install

      - name: unit testing
        id: unit-test-1
        run: npm test

      - name: Archive Test Result
        if: success() && steps.unit-test-1.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: mocha-test-results
          path: test-results.xml

      - name: status
        if: always()
        run: echo "success"

  code-coverage:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4
      - name: setup node js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path:  node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: install
        run: npm install

      - name: check code coverage
        run: npm run coverage
        continue-on-error: true

      - name: Archive Coverage Reports
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage
          retention-days: 5

  docker:
    runs-on: ubuntu-latest
    needs: [build_test,code-coverage]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build And Push
        uses: docker/docker-push@v3
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}

      - name: Docker Image Testing
        run: |
          docker images
          docker run --name solar-system-app -d \
            -p 8080:3000 \
            -e MONGO_URI=$MONGO_URI \ 
            -e MONGO_USERNAME=$MONGO_USERNAME \
            -e MONGO_PASSWORD=$MONGO_PASSWORD \
            ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
          
          export IP=$( docker inspect -f '{{ range .NetworkSettings.Networks }}{{ .IPAddress }} {{ end }}' solar-system-app )
          echo IP
          
          echo checking url using wget
          wget -q -o 127.0.0.1:8080/live | grep  live


