name: Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install
        run: npm install

      - name: run test
        run: npm test
