name: Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
env:
  MONGO_URI: 'mongodb+srv://cluster0.vihfcne.mongodb.net/myappdb?authSource=admin&retryWrites=true&w=majority'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install
        run: npm install

      - name: run test
        run: npm run test
