name: Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
env:
  MONGO_URI: ${{ vars.MONGO_URI }}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
  build_test:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        versions: [18,19,20]
        os: [ubuntu-latest,windows-latest]
        exclude:
          - versions: 18
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:

      - name: checkout
        uses: actions/checkout@v4
      - name: check files
        run: ls

      - name: setup nodejs on ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.versions }}

      - name: installing on ${{ matrix.os }}
        run: npm install

      - name: unit testing on ${{ matrix.os }}
        run: npm test

      - name: Archive Test Result
        uses: actions/upload-artifact@v4
        with:
          name: mocha-test-results
          path: test-results.xml

      - name: status
        run: echo "success"
