name: My First Workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the codebase
        uses: actions/checkout@v3
      - name: Welcome
        run: echo "welcome"
      - name: List Files
        run: ls
      - name: Read dockerfile
        run: cat Dockerfile