name: Generate Ascii dragon
on: push
jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout codebase
        uses: actions/checkout@v3
      - name: Executing script
        run: |
          chmod +x ascii-script.sh
          ./ascii-script.shg