name: Reusable Workflow For Deployment
on:
  workflow_call:
    inputs:
      mongodb-uri:
        type: string
        required: true
      environment:
        type: string
        required: true
        description: provide the deployment environment
        default: development
    secrets:
      mongodb-password:
        required: true
jobs:
  resuse-deploy:
    name: ${{ inputs.environment }} - deploy
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: configuring k8 environment
        uses: helm/kind-action@v1.4.0
        with:
          cluster_name: test-cluster

      - name: test environment
        run: |
          kubectl get nodes

      - name: create secrets
        run: |
          kubectl create namespace ${{ vars.NAMESPACE }}
          kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
              --from-literal=MONGO_URI="${{ inputs.MONGO_URI }}" \
              --from-literal=MONGO_USERNAME="${{ vars.MONGO_USERNAME }}" \
              --from-literal=MONGO_PASSWORD="${{ secrets.mongodb-password }}" \
              --dry-run=client \
              -o yaml | kubectl apply -f -
          
          kubectl get secrets -n ${{ vars.NAMESPACE }} mongo-db-creds -o yaml

      - name: Replace Token in manifest files
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["kubernetes/development/*.yaml"]'
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ github.sha }}

      - name: creating deployment
        run: |
          kubectl apply -f kubernetes/development                          
          kubectl get pods -n ${{ vars.NAMESPACE }} -o wide