name: check on multiple operating system
on: push
jobs:
  check:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ ubuntu-latest , windows-latest ]
        images: [ alpine , hello-world ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: running on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}